name: 'Deploy to production'
on:
  push:
    branches: [develop]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v3

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - uses: azure/docker-login@v1
        with:
          login-server: gamatest.azurecr.io
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build . -t gamatest.azurecr.io/production:${{ github.sha }}
          docker push gamatest.azurecr.io/production:${{ github.sha }}
      - uses: azure/webapps-deploy@v2
        with:
          app-name: 'backoffice-website'
          images: 'gamatest.azurecr.io/production:${{ github.sha }}'

      - name: Azure logout
        run: |
          az logout
